# Generated by Django 4.1.2 on 2022-11-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_article_articles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
