# Generated by Django 4.1.2 on 2022-11-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_delete_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.AddField(
            model_name='task',
            name='reminder',
            field=models.BooleanField(default=True),
        ),
    ]
