# Generated by Django 4.1.2 on 2022-11-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_reminder_task_reminders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminders',
        ),
        migrations.AddField(
            model_name='task',
            name='reminder',
            field=models.BooleanField(default=False),
        ),
    ]
